// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IValidator is an autogenerated mock type for the IValidator type
type IValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: body
func (_m *IValidator) Validate(body interface{}) error {
	ret := _m.Called(body)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewIValidator creates a new instance of IValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIValidator(t mockConstructorTestingTNewIValidator) *IValidator {
	mock := &IValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
